"use strict";
exports.__esModule = true;
var telefono_1 = require("./telefono");
var telefonoConCamara_1 = require("./telefonoConCamara");
var telefonoConRadio_1 = require("./telefonoConRadio");
var telefono = new telefono_1.Telefono(true, 50);
var tcc = new telefonoConCamara_1.TelefonoConCamara(true, 60);
var tcr = new telefonoConRadio_1.TelefonoConRadio(true, 90, 95.4);
console.log('-------------- Telefono --------------');
telefono.mandarMensaje('Hola');
telefono.hacerLlamada(123456789);
telefono.prenderApagar();
telefono.cargarBateria(20);
console.log('\n');
console.log('-------------- Telefono Con Camara --------------');
tcc.mandarMensaje('Hola');
tcc.hacerLlamada(123456789);
tcc.prenderApagar();
tcc.cargarBateria(20);
tcc.sacarFoto();
console.log('\n');
console.log('-------------- Telefono Con Radio --------------');
tcr.mandarMensaje('Hola');
tcr.hacerLlamada(123456789);
tcr.prenderApagar();
tcr.cargarBateria(20);
tcr.verFrecuenciaActual();
