"use strict";
exports.__esModule = true;
var autoCiudad_1 = require("./autoCiudad");
var autoDeportivo_1 = require("./autoDeportivo");
var camioneta_1 = require("./camioneta");
var fitito = new autoCiudad_1.AutoCiudad('Fiat', '500', 'Rojo');
fitito.tooglePrendido();
fitito.tooglePrendido();
fitito.tooglePrendido();
fitito.acelerar(170);
fitito.acelerar(140);
fitito.frenar(15);
console.log(fitito.getVelocidad());
fitito.frenarEnSeco();
console.log(fitito.getVelocidad());
console.log(fitito.getColor());
console.log(fitito.getMarca());
console.log(fitito.getModelo());
console.log('----------------------------------');
var nave = new autoDeportivo_1.AutoDeportivo('Ford', 'Mustang', 'Negro');
nave.tooglePrendido();
nave.tooglePrendido();
nave.tooglePrendido();
nave.acelerar(170);
nave.frenar(15);
console.log(nave.getVelocidad());
nave.frenarEnSeco();
console.log(nave.getVelocidad());
console.log(nave.getColor());
console.log(nave.getMarca());
console.log(nave.getModelo());
console.log('----------------------------------');
var chata = new camioneta_1.Camioneta('Toyota', 'Hilux', 'Blanco');
chata.tooglePrendido();
chata.tooglePrendido();
chata.tooglePrendido();
chata.acelerar(170);
chata.acelerar(140);
chata.frenar(15);
console.log(chata.getVelocidad());
chata.frenarEnSeco();
console.log(chata.getVelocidad());
console.log(chata.getColor());
console.log(chata.getMarca());
console.log(chata.getModelo());
